# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('contact_updated', models.DateField(auto_now_add=True)),
                ('group_status', models.CharField(max_length=20)),
                ('admin', models.CharField(max_length=20)),
                ('admin_status', models.CharField(max_length=20)),
                ('frequency', models.IntegerField()),
                ('frq_scale', models.CharField(blank=True, max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('posts', models.ManyToManyField(to='posts.Post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
