# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('control', '0002_auto_20170809_2306'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(through='control.Control', to='posts.Post'),
        ),
    ]
