# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='frq_scale',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
