# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_status',
            field=models.CharField(choices=[('1', 'ok'), ('2', 'waiting in'), ('3', 'waiting admin')], max_length=20),
        ),
    ]
