# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170725_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='frq_scale',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
    ]
