# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170816_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_status',
            field=models.CharField(choices=[('ok', 'ok'), ('waiting in', 'waiting in'), ('waiting admin', 'waiting admin'), ('admin ignored', 'admin ignored')], max_length=20),
        ),
    ]
