# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170727_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
