# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170727_2313'),
        ('groups', '0005_auto_20170728_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
