# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170816_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin_status',
        ),
    ]
