# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_status',
            new_name='status',
        ),
    ]
