# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20170817_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('nok', 'nok'), ('waiting in', 'waiting in'), ('waiting admin', 'waiting admin'), ('admin ignored', 'admin ignored')], max_length=20),
        ),
    ]
