# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20170817_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[(1, 'ok'), (2, 'nok'), (3, 'waiting in'), (4, 'waiting admin'), (5, 'admin ignored')], max_length=20),
        ),
    ]
