# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20170809_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['published']},
        ),
    ]
