# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170727_2313'),
        ('groups', '0005_auto_20170728_2011'),
        ('control', '0002_auto_20170728_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='control',
            name='object_id',
        ),
        migrations.AddField(
            model_name='control',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
