# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20170729_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='post',
        ),
    ]
